# Generated by Django 4.0.5 on 2022-06-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='offer',
            new_name='open',
        ),
    ]
