# Generated by Django 4.0.5 on 2022-07-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company'),
        ),
    ]
